name: Build & Push Image

on:
  workflow_dispatch:     # lancement manuel
    inputs:
      channel:
        description: "Choisis alpha / beta / stable"
        required: false
        default: beta
        type: choice
        options:
          - alpha
          - beta
          - stable

jobs:
  build:
    runs-on: docker
    permissions:
      packages: write
      contents: read

    steps:
      - name: Install Node.js
        run: apk add --no-cache nodejs npm docker
        if: runner.os == 'Linux'

      - uses: actions/checkout@v4

      # --- Login au registre Gitea ---
      - name: Login manuellement
        run: echo "${{ secrets.CI_TOKEN }}" | docker login gitea.necos.cloud -u "${{ github.actor }}" --password-stdin

      # --- Build & push avec buildx ---
      - uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ${{ env.CI_SERVER_HOST }}/${{ env.CI_REPOSITORY }}/:${{ inputs.channel }}
            ${{ env.CI_SERVER_HOST }}/${{ env.CI_REPOSITORY }}:${{ github.sha }}
          platforms: linux/amd64,linux/arm64
          provenance: false              # optionnel : accélère le push

