name: Build & Push Image

on:
  workflow_dispatch:     # lancement manuel
    inputs:
      channel:
        description: "Choisis alpha / beta / stable"
        required: false
        default: beta
        type: choice
        options:
          - alpha
          - beta
          - stable

jobs:
  build:
    runs-on: docker
    permissions:
      packages: write
      contents: read

    steps:
      - uses: actions/checkout@v4

      # --- Login au registre Gitea ---
      - uses: docker/login-action@v3
        with:
          registry: ${{ env.CI_SERVER_HOST }}
          username: "FrostyPinkPlume"
          password: "${{ secrets.CI_TOKEN }}"

      # --- Build & push avec buildx ---
      - uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ${{ env.CI_SERVER_HOST }}/${{ env.CI_REPOSITORY }}/:${{ inputs.channel }}
            ${{ env.CI_SERVER_HOST }}/${{ env.CI_REPOSITORY }}:${{ github.sha }}
          platforms: linux/amd64,linux/arm64
          provenance: false              # optionnel : accélère le push

